version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network

  service-b:
    build:
      context: ./go-weather-api 
      dockerfile: Dockerfile
    container_name: service-b
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    depends_on:
      - zipkin
    networks:
      - app-network

  service-a:
    build:
      context: ./service-a 
      dockerfile: Dockerfile
    container_name: service-a
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SERVICE_B_URL=http://service-b:8081
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - service-b
      - zipkin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

